### ISSUE TITLE
use slf4j instead of java.util.logging

### ISSUE THREAD

**Issue by exaV** [Viascom/FoxHttp#19]
The default logger uses JUL which is hardy ever used in modern applications. It would be nice if FoxHttp just used the slf4j-api like many other Java frameworks.
It would allow users to be flexible with the loggging-implementation while still providing logging out of the box.

**Comment by patrickboesch** [comment]
see [Slf4jLogger](https://github.com/Viascom/FoxHttp/blob/master/src/main/java/ch/viascom/groundwork/foxhttp/log/Slf4jLogger.java)
