### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by ThomasKagerer** [Viascom/FoxHttp#8]
I get the following error:

`2018-05-02 08:27:45.282 ERROR 5 --- [nio-8080-exec-6] c.u.s.c.s.e.GlobalExceptionHandler       : java.util.ConcurrentModificationException
  | at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1701)
  | at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
  | at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
  | at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
  | at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
  | at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  | at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
  | at ch.viascom.groundwork.foxhttp.authorization.DefaultAuthorizationStrategy.removeAuthorizationByKey(DefaultAuthorizationStrategy.java:111)
  | at ch.viascom.groundwork.foxhttp.authorization.DefaultAuthorizationStrategy.replaceAuthorization(DefaultAuthorizationStrategy.java:141)
  | at ch.umb.solutions.curo.themis.apis.camunda.CamundaApiFactory.setJwt(CamundaApiFactory.java:59)
  | at ch.umb.solutions.curo.themis.apis.camunda.CamundaApiFactory.getApi(CamundaApiFactory.java:69)
  | at ch.umb.solutions.curo.themis.apis.camunda.CamundaApiFactory.getTaskApi(CamundaApiFactory.java:42)
  | at ch.umb.solutions.curo.themis.controllers.TasksController.getTaskList(TasksController.java:137)
  | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
  | at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
  | at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
  | at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:870)
  | at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:776)
  | at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
  | at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
  | at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
  | at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:978)
  | at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:870)
  | at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
  | at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:855)
  | at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
  | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
  | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
  | at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
  | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
  | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
  | at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:158)
  | at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:126)
  | at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:111)
  | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
  | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
  | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
  | at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:84)
  | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
  | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
  | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
  | at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
  | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
  | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
  | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
  | at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
  | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
  | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
  | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
  | at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
  | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
  | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
  | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
  | at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
  | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
  | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
  | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
  | at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
  | at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
  | at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
  | at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
  | at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
  | at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
  | at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
  | at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
  | at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
  | at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
  | at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
  | at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
  | at java.lang.Thread.run(Thread.java:748)`

After having a look into the source code at DefaultAuthorizationStrategy.removeAuthorizationByKey:111, my assumption is the content of foxHttpAuthorizations.get(scope.toString()).entrySet() is being changed by another thread while looping over it.

Unfortunately I couldn't neither reproduce it a second time nor did I dig deeper.

**Comment by patrickboesch** [comment]
Hot-Fix for DefaultAuthorizationStrategy is available in [branche 1.3.3](https://github.com/Viascom/FoxHttp/tree/version_1.3.3). Full ConcurrentModificationException fix for all strategies is in development and will be released in version 1.3.3

**Comment by patrickboesch** [comment]
Version 1.3.4 is released.
